// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorTracker.DataAcessLayer;

#nullable disable

namespace SensorTracker.DataAcessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230528150620_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensorTracker.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SensorTracker.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "С засыпкой",
                            Name = "K1",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "С засыпкой",
                            Name = "К1У",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "С засыпкой",
                            Name = "K2",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "С засыпкой",
                            Name = "K2-KP",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "С засыпкой",
                            Name = "K2.1",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "С засыпкой",
                            Name = "K2T",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 7,
                            Description = "С засыпкой",
                            Name = "К2Ф",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "С засыпкой",
                            Name = "K3",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 10,
                            Description = "С засыпкой",
                            Name = "K4",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 11,
                            Description = "С засыпкой",
                            Name = "K4P",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 12,
                            Description = "С засыпкой",
                            Name = "K4.1",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 13,
                            Description = "С засыпкой",
                            Name = "K5",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 14,
                            Description = "С засыпкой",
                            Name = "К1И",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 15,
                            Description = "С засыпкой",
                            Name = "ТКЖ",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 16,
                            Description = "С засыпкой",
                            Name = "IT-8 RUT",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 17,
                            Name = "K1",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 18,
                            Name = "K2",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 19,
                            Name = "K2.1",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 20,
                            Name = "K3",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 21,
                            Name = "K4",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 22,
                            Name = "K5",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 23,
                            Name = "K2Ф",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 24,
                            Name = "K2М",
                            Price = 37.0
                        },
                        new
                        {
                            Id = 25,
                            Name = "K0",
                            Price = 45.0
                        },
                        new
                        {
                            Id = 26,
                            Name = "K9",
                            Price = 58.0
                        },
                        new
                        {
                            Id = 27,
                            Name = "K10",
                            Price = 45.0
                        },
                        new
                        {
                            Id = 28,
                            Name = "K1И-КП",
                            Price = 52.0
                        },
                        new
                        {
                            Id = 29,
                            Name = "",
                            Price = 52.0
                        });
                });

            modelBuilder.Entity("SensorTracker.Entities.Order", b =>
                {
                    b.HasOne("SensorTracker.Entities.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId");

                    b.Navigation("Sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
